### ISSUE TITLE
Submission to iTunes Connect Failed

### ISSUE THREAD

**Issue by valeIT** [freshdesk/mobihelp-ios#10]
https://infinit.io/_/3eXQHFx

**Comment by kjantzer** [comment]
@valeIT Make sure to copy the necessary mobihelp frameworks to your project and add them to linked binaries

![screen shot 2015-10-20 at 11 13 09 am](https://cloud.githubusercontent.com/assets/467487/10616746/95329d76-771b-11e5-8afa-4062abdf6747.png)

**Comment by valeIT** [comment]
Really sorry for the late reply, I'm using Cocoapod, if wanted to do the manual linking I'd have included the library directly (sorry for not saying it before).

**Comment by hrishikesh-p** [comment]
This is fixed in the latest version of the SDK.
