### ISSUE TITLE
On iOS Is there any way to present feedback with custom message?

### ISSUE THREAD

**Issue by meeramohideen** [freshdesk/mobihelp-ios#13]
On iOS can we autofill the message instead of showing the placeholder message ("What do you want to talk to us about?") while presenting feedback view? So user can just type email/Name if required and submit the ticket?

**Comment by hrishikesh-p** [comment]
This is not currently possible. However you could set the name and email .. so that the user just needs to key in the concern. 

We will consider this feature for a future release.

**Comment by meeramohideen** [comment]
Okay thanks, I guess its available on Android, I've seen people using it. Is there any other reason not to include this feature on iOS SDK.

**Comment by hrishikesh-p** [comment]
This has been added on the SDK in version 1.6.6 . Please check .
