### ISSUE TITLE
Swift, Cocoapods and use_frameworks! flag: cannot find the module

### ISSUE THREAD

**Issue by demetrio812** [freshdesk/mobihelp-ios#14]
Hello,
I'm integrating the SDK in a Swift project, I use the use_frameworks! flag in my Podfile. It correctly find the library but I'm not be able to use it as it doesn't recognise it as a module.

Any suggestions?

**Comment by rdougan** [comment]
I'm having the same issue

**Comment by rdougan** [comment]
I found this: https://github.com/AravinthChandran/Mobihelp-Swift-Sample

You have to manually create a bridging header file and import it there. Then you can use the Mobihelp SDK as normal.

**Comment by hrishikesh-p** [comment]
Thanks for sharing the solution @rdougan
