### ISSUE TITLE
Custom font is not visible when submitting a ticket

### ISSUE THREAD

**Issue by sasikiran** [freshdesk/mobihelp-ios#15]
Hi,
 When using custom fonts for the theme, everything seems to update correctly, except the ticket submission screen. We are not able to see what the user is typing on in the screen. Is this a bug?

![img_6388](https://cloud.githubusercontent.com/assets/1332828/12775739/5c82042c-ca76-11e5-994e-c2b9d35a1bd6.PNG)

**Comment by sasikiran** [comment]
**Update**: Issue is resolved. Please close this. The problem was I swapped font name and size values in the plist. Thanks.

**Comment by hrishikesh-p** [comment]
Thank you for the update .
