### ISSUE TITLE
Translate strings using Cocoapods

### ISSUE THREAD

**Issue by hufkens** [freshdesk/mobihelp-ios#16]
Hi we use the SDK in our app but we need to localise the strings to Dutch. Preferably always because the app is Dutch only.

In the docs this is mentioned:
`Almost every single piece of text used in Mobihelp is customizable. Just edit the “MHLocalizable.strings” file that contains all the strings used in Mobihelp.`

But we have the SDK added through a the Pod and changing the original MHLocalizable.strings file is not a good idea. I added a new file to the app but it won't take the translated strings.

Any idea how we can integrate translations using the Podfile?

**Comment by jedi4ever** [comment]
@hrishikesh-p :zap:

**Comment by vitorleal** [comment]
I have the same problem with cocoaPods instal, i need to translate it to other languages but i cant .

**Comment by gugarush** [comment]
Same problem here. @hufkens, did you find any solution?

**Comment by hrishikesh-p** [comment]
Let me first  apologize for the delay in getting to this. 

You can now set a override strings files for localization. For example. if your values are in a file (can be part of your project)  called `MyAppTexts.strings` then you can set it as follows. 

```Objective-C
[config setLocalizationName:@"MyAppTexts"];
```

This fix is available in https://github.com/freshdesk/mobihelp-ios/releases/tag/v1.6.6
