### ISSUE TITLE
Doesn't seem to work with swift?

### ISSUE THREAD

**Issue by donaldpiret** [freshdesk/mobihelp-ios#17]
Tried using the cocoapods integration and it can't find the framework or import anything. Any chance of getting this working with Swift?

**Comment by ObjectiveB** [comment]
Hi  
   
 Could you please elaborate the issue for us.  
   
 Check your ticket status - https://support.freshdesk.com/helpdesk/tickets/535159 
 
  Regards 
 Kanna 
 
  
         On Fri, 25 Mar at 11:03 PM
          ,  freshdesk/mobihelp-ios <reply@reply.github.com>  wrote:
           Tried using the cocoapods integration and it can't find the framework or import anything. Any chance of getting this working with Swift?

**Comment by hrishikesh-p** [comment]
Can you please check the sample listed at  https://github.com/AravinthChandran/Mobihelp-Swift-Sample

It should work fine with Swift. Please reopen this if otherwise.

**Comment by donaldpiret** [comment]
Got it to work, thank you. Hadn't figured out that I needed to create the Bridging header file, even when installing it via the Pods.
