### ISSUE TITLE
Theming with cocoapods

### ISSUE THREAD

**Issue by Tobi3112** [freshdesk/mobihelp-ios#19]
What pattern do you suggest when using cocoa pods for theming and localisation? 

The only info I found was the one in the release notes:
SDK now allows overriding the default Localization File when using cocoapods.  
Thanks

**Comment by hrishikesh-p** [comment]
Hi @Tobi3112  

The SDK looks for the file in your app's Resources before looking up in the SDK's bundle.

So for Theming, You could just copy over the Theme file to your project and customize it. 

As for Localization, You could do the same , but you need to rename the file to provide the override values. 

You can now set a override strings files for localization. For example. if your values are in a file (can be part of your project) called MyAppTexts.strings then you can set it as follows.

```Objective-C
[config setLocalizationName:@"MyAppTexts"];
```
