### ISSUE TITLE
Custom theme hides "new conversation" button

### ISSUE THREAD

**Issue by dccarmo** [freshdesk/mobihelp-ios#2]
I'm using Mobihelp 1.3.3 and if I set a custom theme on `AppDelegate` (a theme derived from the `FDLightTheme`), when I present the support screen (through `presentSupport:), it doesn't show the "new conversation" and search buttons.

The workaround I'm currently using is editing the `FDLightTheme` directly in the bundle, but it's not ideal.

**Comment by hrishikesh-p** [comment]
The Theming expects the images name to include the Theme name. hope you have renamed the images to include your theme name.

e.g SearchButtonFDLightTheme@2x.png need to be rename to SearchButtonYourThemeName@2x.png

**Comment by harlanhaskins** [comment]
This should be specified in documentation.

**Comment by dccarmo** [comment]
By the way I tried the suggested solution, but couldn't make it work.
