### ISSUE TITLE
Use Dynamic Text instead of explicit family names.

### ISSUE THREAD

**Issue by harlanhaskins** [freshdesk/mobihelp-ios#3]
Mobihelp looks out of place on iOS 9 because of defaulting to HelveticaNeue.

Font sizes to not adjust with the users' preference in the Settings app.

**Comment by hrishikesh-p** [comment]
We are looking into this.

**Comment by hrishikesh-p** [comment]
@harlanhaskins  Thanks for the suggestion . We have fixed this with version 1.6 . By default , the SDK will use the Systems default font and Dynamic font sizes . You can override them from the theme file.
