### ISSUE TITLE
Custom theme hide buttons

### ISSUE THREAD

**Issue by popei69** [freshdesk/mobihelp-ios#5]
Hey,

I've just copied the FDLightTheme file to update it, I changed only the name, and when using it, the actual view doesn't display the search icon and the write icon (two right buttons in UINavigationBar).

It seems that these two buttons are only available via the two defaults themes. Is there a check on the themeName that disable these two buttons?

I tried on my personal project, but also with your sample project, I can't see search buttons and write buttons with my "custom" theme.

It's not working on v1.3.3 and v1.5.2

Is there any solution to work around this issue?

**Comment by hrishikesh-p** [comment]
The icons for search and conversation are setup as images. These images need to be in the format <image name><theme name>.PNG . some examples are included in the integration guide . 

http://developer.freshdesk.com/mobihelp/


The images are located in MHResources.bundle . Can you please rename and try ?

**Comment by iamabhiee** [comment]
I am facing the same issue while trying to integrate via cocoapods

**Comment by hrishikesh-p** [comment]
@iamabhiee  Abishek, Are the icons renamed to match your theme name ? e.g LeftBubbleFDLightTheme@2x.png. 

You can also have a copy of the theme file outside the SDK ( in your main project at the top level) for easy maintenance and updates.

**Comment by iamabhiee** [comment]
Yes I am doing that
Can you check my sample project? It would help you to know if I am missing something. 

https://www.dropbox.com/s/305cn3ny051b77d/MobihelpTest.zip?dl=0

**Comment by hrishikesh-p** [comment]
@iamabhiee Mobihelp currently expects the images to be part of a bundle "MHResources.bundle" . So theming the images is a little convoluted. 

You need to rename the files inside the MHResource.bundle directly. This needs to be done in the bundle file installed as part of the Pod install. 

We are improving theming options in the next release .

**Comment by iamabhiee** [comment]
@hrishikesh-p Can you show me how to do that in sample project that I have provided?

**Comment by AravinthChandran** [comment]
In the MobihelpTest workspace choose Pods XcodeProject from the left pane. You can locate the bundle by exploring the following path, Pods/MobihelpSDK/Resources/MHResources.bundle . Once you do, You can directly rename the images in the bundle .

You can find your updated sample project here,
https://www.dropbox.com/s/ymofmvnz7flztmv/MobihelpTest.zip?dl=0

**Comment by harlanhaskins** [comment]
And if you Pod Install, these changes are overwritten.

**Comment by hrishikesh-p** [comment]
Yes. Unfortunately. This is a workaround. We are testing a better solution . We will update once it is ready

**Comment by iamabhiee** [comment]
Any updates?

**Comment by hrishikesh-p** [comment]
Can you please try our latest SDK version 1.6 . 

You can specify the custom images in the theme file. Also, the theme file can be part of your project outside the bundle. So if you reinstall the pod you wont lose the changes .
