### ISSUE TITLE
ENABLE_BITCODE errors. ios9 - mobihelp 1.5.2

### ISSUE THREAD

**Issue by maddoggy1979** [freshdesk/mobihelp-ios#6]
I am having trouble testing my app on a device, getting the error below. Everything works fine in the simulator, (for latest ios9 beta) but fails to build for a device.
None of the general suggestions on stackoverflow etc work to fix this problem.

Any suggestions? I am using cocoapods which has updated mobihelp to 1.5.2
I know ios is still in beta, but this is stopping me from testing certain functions on a device which aren't available on a simulator.

```
ld: '/Users/xxxxx/Documents/Apps/xxxxx/Pods/MobihelpSDK/MobihelpSDK/libFDMobihelpSDK.a
(FDTicketsUpdater.o)' does not contain bitcode. You must rebuild it with bitcode enabled 
(Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for 
this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by hrishikesh-p** [comment]
The SDK has not been built with bit code enabled so the library cannot be used with builds that expect bit_code to be enabled . We are working on this issue .

**Comment by maddoggy1979** [comment]
Well it looks like my issue is solved once I finally found the ENABLE_BITCODE setting in XCode and set it to NO. Presumably this will still be an issue though for people with WatchKit etc.
Thanks

**Comment by dccarmo** [comment]
It'd be great to have bitcode support to improve app thinning. Any updates on this?

**Comment by hrishikesh-p** [comment]
v1.6.2 has been added to Cocoapods with bitcode enabled build . Please check let us know in case of suggestions or concerns.
