### ISSUE TITLE
Is there any way to use Support via Storyboard?

### ISSUE THREAD

**Issue by popei69** [freshdesk/mobihelp-ios#7]
Hi guys, I would like to use storyboard and segues instead of the programmatical way to present Support. It's mostly because I use a UITabBarController that's already done for Storyboard.

I've checked the sample project, but it's not used with storyboard file.

Thanks,
Ben

**Comment by hrishikesh-p** [comment]
It is possible to use Freshdesk SDK with a story board. It is not much different. you could refer the swift sample hosted here -> https://github.com/AravinthChandran/Mobihelp-Swift-Sample
