### ISSUE TITLE
Crash from new version 1.6.0

### ISSUE THREAD

**Issue by iamabhiee** [freshdesk/mobihelp-ios#8]
Hi

After upgrading to latest version I found that it crashes on selection of any of the solution.

**Comment by hrishikesh-p** [comment]
Can you please give the some exception stack trace or error ?

**Comment by iamabhiee** [comment]
Sure following is the stack trace 

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'
*** First throw call stack:
(0x183f8c22c 0x195c000e4 0x183e78668 0x183e78498 0x1001c6afc 0x1001c61d8 0x188a08a6c 0x188a0877c 0x188bab044 0x188abdcd8 0x188abdaa4 0x188abda24 0x188a05548 0x188341db8 0x18833c820 0x18833c6c4 0x18833be58 0x18833bbd8 0x188335300 0x183f43ff0 0x183f40f7c 0x183f4135c 0x183e6cf74 0x18d8cf6fc 0x188a6ed94 0x100145664 0x1962aaa08)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by hrishikesh-p** [comment]
@iamabhiee  Can you please check v1.6.1 . We have fixed an issue affecting certain accounts . ( API response )
